### ISSUE TITLE
`FileInput` implementations

### ISSUE THREAD

**Issue by Jhsmit** [Jhsmit/awesome-solara#2]
I have implemented two versions of `ipyvuetify.extra.FileInput`. They both more or less work and I'm looking for feedback on the implementation. 

They are in `awesome_solara.components.<file_input / file_input_handler>`.  The  `file_input.py` implementation is copy/paste of the solara `FileDrop`.
The implementation from  `_handler` attaches a handler as shown in the [medium post on reactive](https://maartenbreddels.medium.com/advance-your-ipywidget-app-development-with-reacton-6734a5607d69)

I understand why we need to use `use_effect`, but are there pro/cons to each approach?
The  `_handler` returns a cleanup function, the other does not, is that here not required since we do not attach any handler to the widget?

**Comment by maartenbreddels** [comment]
The `use_effect` method is not something you should do, since you get the same effectively as the use_effect method, but with less code. The use_effect method is great for understanding how it (almost) works under the hood though!

Reacton will automatically clean up event handlers that were attached due to the use of `on_<name>`, so no need :)

**Comment by Jhsmit** [comment]
If I don't use `use_effect`, how do i get access to the underlying 'real' widget, and thereby the data that was uploaded?

**Comment by maartenbreddels** [comment]
Ah, for that, you do need, use_effect. So the `wire_files` is needed, but the `attach_handler` should be considered only for understanding.
